# Hillier & Grinblatt: Chapter 1: Raising Capital: The Process and the Players

Text

## Pre-lecture notes

Text

## Lecture notes

Text

## Exercises

### Exercise 1.1

*Competitive underwritings appear to be cheaper than negotiated ones, but almost no firm use the former. Can you give some reasons for this?* [@book, p.26]

### Exercise 1.2

*Insider dealing is illegal in most countries. What re the costs and benefitsof prohibiting insider dealing?* [@book, p.26]

### Exercise 1.3

*Many companies simultaneously issue both equity and debt. Explain why toy think they would do this.* [@book, p.26]

### Exercise 1.4

*Small firms tend to raise funds from private investors and venture capitalists. As these firms grow larger, they focus more on raising capital from the organized capital markets. Explain why this occurs.* [@book, p.26]

### Exercise 1.5

*In emerging markets, the functioning of primary markets is not as yet well established. As a result, alternative methods of raising funds must be approached by firms operating in this environment. Discuss the issues that companies face in raising funds in emerging markets.* [@book, p.26]

### Exercise 1.6

*Investment banks that are successful in raising capital for companies tend to be used to advise on merger and takeover activities. Why do you think this happens? Discuss.* [@book, p.26]

### Exercise 1.7

*What are the principles underlying Islamic financing? Explain how Islamic bank could replicate the products of Western banks. Provide some hypothetical examplesto support your answer.* [@book, p.26]

### Exercise 1.8

*What is the difference between internal financing and external financing? Review the factors that influence a firm's choice between external and internal financing.* [@book, p.26]

### Exercise 1.9

*You plan to raise funds through following Islamic principles. You require funding today of 10 billion Bahraini dinars, and would like to pay it back in equal amounts over 10 yearsin monthly instalments. How would you do this?* [@book, p.26]